---
name: Generate commit logs

on:
  push:
    tags-ignore:
      - "*"
  pull_request:
  schedule:
    - cron: "42 10 * * 1"

jobs:
  generate-commit-logs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generating commit logs
        run: |
          cd commits && ./generate.sh -t 1
